// Package native — kernel module codegen.
//
// Two outputs from a parsed Manifest:
//
//   1. glue.c    — a C file with PyInit_<module>, a PyMethodDef table,
//                  and one wrapper per function that does PyArg_ParseTuple,
//                  calls the user's exported symbol, and converts the result.
//   2. <name>.pyi — a Python stub file with typed signatures and
//                   docstrings, for IDE / mypy / pyright integration.
//
// Both consume the same `Manifest` shape so a single source of truth
// (the .molt.toml) drives runtime behaviour and static type info.

package native

import (
	"fmt"
	"io"
	"os"
	"strings"
)

// ── primitive type table ─────────────────────────────────────────────────────

// kernelPrimitive is a recognised manifest type. Anything outside the
// table causes the function to be dropped from the binding (with a warning).
type kernelPrimitive struct {
	manifestName string // "i32", "f32", ...
	cTypeName    string // C type spelling
	pyArgFmt     string // PyArg_ParseTuple format char
	pyArgVarType string // C variable type for the parse destination
	pyReturnTpl  string // template for wrapping a value into PyObject*
	pyTypeName   string // Python annotation in .pyi
	isVoid       bool
}

var kernelPrimitives = []kernelPrimitive{
	{"void", "void", "", "", "Py_RETURN_NONE", "None", true},
	{"bool", "_Bool", "p", "int",
		"PyBool_FromLong((long)(%s))", "bool", false},
	{"i8", "int8_t", "i", "int",
		"PyLong_FromLong((long)(%s))", "int", false},
	{"i16", "int16_t", "i", "int",
		"PyLong_FromLong((long)(%s))", "int", false},
	{"i32", "int32_t", "i", "int",
		"PyLong_FromLong((long)(%s))", "int", false},
	{"i64", "int64_t", "L", "long long",
		"PyLong_FromLongLong((long long)(%s))", "int", false},
	{"isize", "ssize_t", "L", "long long",
		"PyLong_FromLongLong((long long)(%s))", "int", false},
	{"u8", "uint8_t", "I", "unsigned int",
		"PyLong_FromUnsignedLong((unsigned long)(%s))", "int", false},
	{"u16", "uint16_t", "I", "unsigned int",
		"PyLong_FromUnsignedLong((unsigned long)(%s))", "int", false},
	{"u32", "uint32_t", "I", "unsigned int",
		"PyLong_FromUnsignedLong((unsigned long)(%s))", "int", false},
	{"u64", "uint64_t", "K", "unsigned long long",
		"PyLong_FromUnsignedLongLong((unsigned long long)(%s))", "int", false},
	{"usize", "size_t", "K", "unsigned long long",
		"PyLong_FromUnsignedLongLong((unsigned long long)(%s))", "int", false},
	{"f32", "float", "f", "float",
		"PyFloat_FromDouble((double)(%s))", "float", false},
	{"f64", "double", "d", "double",
		"PyFloat_FromDouble((double)(%s))", "float", false},
}

func lookupPrimitive(name string) (kernelPrimitive, bool) {
	if name == "" {
		return kernelPrimitives[0], true // treat empty return as void
	}
	for _, p := range kernelPrimitives {
		if p.manifestName == name {
			return p, true
		}
	}
	return kernelPrimitive{}, false
}

// ── filtering: drop fns with unsupported types ───────────────────────────────

// resolvedFn is a manifest fn whose types have all been validated.
type resolvedFn struct {
	Name        string
	Description string
	Args        []resolvedArg
	Returns     kernelPrimitive
}

type resolvedArg struct {
	Name        string
	Description string
	Type        kernelPrimitive
}

// resolveFunctions filters the manifest's fn list, dropping any with
// unsupported types and emitting a stderr warning for each. The
// returned slice is safe to feed into the glue / pyi emitters.
func resolveFunctions(m *Manifest) []resolvedFn {
	var out []resolvedFn
	for _, fn := range m.Functions {
		if fn.Name == "" {
			continue
		}
		ret, ok := lookupPrimitive(fn.Returns.Type)
		if !ok {
			fmt.Fprintf(stderrSink, "warn: skipping `%s` — unsupported return type %q\n",
				fn.Name, fn.Returns.Type)
			continue
		}
		args := make([]resolvedArg, 0, len(fn.Args))
		argsOK := true
		for i, a := range fn.Args {
			t, ok := lookupPrimitive(a.Type)
			if !ok {
				fmt.Fprintf(stderrSink, "warn: skipping `%s` — unsupported arg %d type %q\n",
					fn.Name, i, a.Type)
				argsOK = false
				break
			}
			if t.isVoid {
				fmt.Fprintf(stderrSink, "warn: skipping `%s` — void argument not allowed\n",
					fn.Name)
				argsOK = false
				break
			}
			args = append(args, resolvedArg{Name: a.Name, Description: a.Description, Type: t})
		}
		if !argsOK {
			continue
		}
		out = append(out, resolvedFn{
			Name: fn.Name, Description: fn.Description,
			Args: args, Returns: ret,
		})
	}
	return out
}

// ── glue.c emission ──────────────────────────────────────────────────────────

// emitGlueC writes the full text of glue.c for a manifest.
func emitGlueC(m *Manifest) string {
	module := m.Module
	fns := resolveFunctions(m)

	var b strings.Builder
	b.WriteString("/* Auto-generated by molt — do not edit. */\n")
	b.WriteString("#define PY_SSIZE_T_CLEAN\n")
	b.WriteString("#include <Python.h>\n")
	b.WriteString("#include <stdint.h>\n")
	b.WriteString("#include <stddef.h>\n\n")

	// Forward-declare each user export.
	for _, fn := range fns {
		b.WriteString("extern ")
		b.WriteString(fn.Returns.cTypeName)
		b.WriteString(" ")
		b.WriteString(fn.Name)
		b.WriteString("(")
		for i, a := range fn.Args {
			if i > 0 {
				b.WriteString(", ")
			}
			b.WriteString(a.Type.cTypeName)
		}
		b.WriteString(");\n")
	}
	b.WriteString("\n")

	// Per-fn wrapper.
	for _, fn := range fns {
		emitWrapperC(&b, fn)
	}

	// Method table.
	b.WriteString("static PyMethodDef _molt_methods[] = {\n")
	for _, fn := range fns {
		fmt.Fprintf(&b, "    {%q, (PyCFunction)py_%s, METH_VARARGS, NULL},\n",
			fn.Name, fn.Name)
	}
	b.WriteString("    {NULL, NULL, 0, NULL}\n")
	b.WriteString("};\n\n")

	// Module def + PyInit.
	fmt.Fprintf(&b, `static struct PyModuleDef _molt_moddef = {
    PyModuleDef_HEAD_INIT,
    %q,         /* m_name */
    NULL,        /* m_doc */
    -1,          /* m_size */
    _molt_methods,
};

PyMODINIT_FUNC PyInit_%s(void) {
    return PyModule_Create(&_molt_moddef);
}
`, module, module)

	return b.String()
}

func emitWrapperC(b *strings.Builder, fn resolvedFn) {
	fmt.Fprintf(b, "static PyObject* py_%s(PyObject* self, PyObject* args) {\n",
		fn.Name)

	// Variable declarations.
	var fmtStr strings.Builder
	for i, a := range fn.Args {
		fmt.Fprintf(b, "    %s _arg%d;\n", a.Type.pyArgVarType, i)
		fmtStr.WriteString(a.Type.pyArgFmt)
	}

	// Parse args.
	if len(fn.Args) > 0 {
		fmt.Fprintf(b, "    if (!PyArg_ParseTuple(args, \"%s\"", fmtStr.String())
		for i := range fn.Args {
			fmt.Fprintf(b, ", &_arg%d", i)
		}
		b.WriteString(")) return NULL;\n")
	} else {
		b.WriteString("    (void)self; (void)args;\n")
	}

	// Call expression with width-correct casts.
	callExpr := fn.Name + "("
	for i, a := range fn.Args {
		if i > 0 {
			callExpr += ", "
		}
		callExpr += fmt.Sprintf("(%s)_arg%d", a.Type.cTypeName, i)
	}
	callExpr += ")"

	if fn.Returns.isVoid {
		fmt.Fprintf(b, "    %s;\n", callExpr)
		fmt.Fprintf(b, "    %s;\n", fn.Returns.pyReturnTpl)
	} else {
		fmt.Fprintf(b, "    %s _ret = %s;\n", fn.Returns.cTypeName, callExpr)
		fmt.Fprintf(b, "    return %s;\n",
			fmt.Sprintf(fn.Returns.pyReturnTpl, "_ret"))
	}
	b.WriteString("}\n\n")
}

// ── .pyi emission ────────────────────────────────────────────────────────────

// emitPyiStub generates a .pyi for the manifest, including parameter
// names and per-function descriptions when provided.
func emitPyiStub(m *Manifest, sourcePath string) string {
	fns := resolveFunctions(m)

	var b strings.Builder
	fmt.Fprintf(&b, "\"\"\"Auto-generated by molt. Source: %s\"\"\"\n\n", sourcePath)

	if len(fns) == 0 {
		b.WriteString("# No exported functions resolved.\n")
		return b.String()
	}

	for _, fn := range fns {
		emitPyiFn(&b, fn)
	}
	return b.String()
}

func emitPyiFn(b *strings.Builder, fn resolvedFn) {
	fmt.Fprintf(b, "def %s(", fn.Name)
	for i, a := range fn.Args {
		if i > 0 {
			b.WriteString(", ")
		}
		name := a.Name
		if name == "" {
			name = fmt.Sprintf("_arg%d", i)
		}
		fmt.Fprintf(b, "%s: %s", name, a.Type.pyTypeName)
	}
	fmt.Fprintf(b, ") -> %s:", fn.Returns.pyTypeName)

	// Emit a docstring if any description metadata is present.
	hasDesc := fn.Description != ""
	for _, a := range fn.Args {
		if a.Description != "" {
			hasDesc = true
			break
		}
	}
	if !hasDesc {
		b.WriteString(" ...\n")
		return
	}

	b.WriteString("\n")
	b.WriteString("    \"\"\"")
	if fn.Description != "" {
		b.WriteString(fn.Description)
	}
	hasArgDoc := false
	for _, a := range fn.Args {
		if a.Description != "" {
			hasArgDoc = true
			break
		}
	}
	if hasArgDoc {
		b.WriteString("\n\n    Args:\n")
		for i, a := range fn.Args {
			name := a.Name
			if name == "" {
				name = fmt.Sprintf("_arg%d", i)
			}
			fmt.Fprintf(b, "        %s: %s\n", name, defaultIfEmpty(a.Description, ""))
		}
	}
	b.WriteString("    \"\"\"\n    ...\n")
}

func defaultIfEmpty(s, dflt string) string {
	if s == "" {
		return dflt
	}
	return s
}

// stderrSink is where resolveFunctions writes its warnings. Defaults
// to os.Stderr; tests can swap in a buffer.
var stderrSink io.Writer = os.Stderr
