"""Demo 21 — Transport Glue (Rust, unix_socket)

Calls Rust compression functions from Python via a persistent unix socket server.
The server starts on first call and stays running — multiple Python threads can
share it concurrently.
"""

import compress  # generated by molt sync
import threading
import time

print("=== Transport Glue: Rust → Python (unix_socket) ===\n")

data = b"Transport Glue demo payload! " * 500
print(f"Original size: {len(data):,} bytes")

# Basic compress/decompress round-trip.
compressed = compress.deflate(data)
print(f"Compressed:    {len(compressed):,} bytes")

decompressed = compress.inflate(compressed)
print(f"Decompressed:  {len(decompressed):,} bytes")

assert decompressed == data, "round-trip mismatch!"
print("✓ Round-trip check passed\n")

r = compress.ratio(data)
print(f"Compression ratio: {r:.4f} ({r*100:.1f}% of original)")

# Demonstrate concurrent access — unix_socket transport supports multiple
# simultaneous callers sharing one Rust server process.
print("\n--- Concurrent stress test (10 threads) ---")
results = [None] * 10
errors = []

def compress_chunk(i: int) -> None:
    chunk = f"chunk {i}: " .encode() + data[:100 * (i + 1)]
    try:
        c = compress.deflate(chunk)
        d = compress.inflate(c)
        results[i] = (len(chunk), len(c), d == chunk)
    except Exception as e:
        errors.append(str(e))

threads = [threading.Thread(target=compress_chunk, args=(i,)) for i in range(10)]
t0 = time.perf_counter()
for t in threads:
    t.start()
for t in threads:
    t.join()
elapsed = time.perf_counter() - t0

if errors:
    print(f"ERRORS: {errors}")
else:
    print(f"All 10 threads completed in {elapsed*1000:.1f} ms")
    for i, (orig, comp, ok) in enumerate(results):
        status = "✓" if ok else "✗"
        print(f"  thread {i+1}: {orig:4} → {comp:4} bytes  {status}")

print("\n✓ Rust glue server handled concurrent Python calls successfully")
