"""Demo 19 — Transport Glue (Go, stdio)

Calls Go functions from Python over a JSON-RPC stdio pipe.
The `stats` module is generated by `molt sync` — the Go binary runs as a
subprocess; no .so, no cgo, no ABI compatibility issues.
"""

import stats  # generated by molt sync

data = [88.0, 92.0, 71.0, 95.0, 84.0, 76.0, 89.0, 93.0, 67.0, 88.0, 91.0, 78.0]

print("=== Transport Glue: Go → Python (stdio) ===\n")

m = stats.mean(data)
s = stats.stddev(data)
print(f"mean:   {m:.2f}")
print(f"stddev: {s:.2f}")

counts = stats.histogram(data, 5)
print(f"\nHistogram ({len(data)} values → 5 buckets):")
for i, c in enumerate(counts):
    bar = "█" * int(c)
    print(f"  bucket {i+1}: {bar} ({c})")

payload = b"Go compression called from Python! " * 200
compressed = stats.compress(payload)
ratio = len(compressed) / len(payload) * 100
print(f"\nCompressed {len(payload):,} bytes → {len(compressed):,} bytes ({ratio:.1f}%)")
print("\n✓ All Go functions called successfully via transport glue")
